# Generated by Django 4.1.7 on 2023-03-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=2000)),
                ('marca', models.CharField(max_length=100)),
                ('surcursal', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=2000)),
                ('mensaje_bienvenida', models.CharField(max_length=2000)),
                ('mensaje_final', models.CharField(max_length=1000)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_actualizada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('respuesta', models.CharField(max_length=2000)),
                ('tipo_pregunta', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_respuesta', models.DateTimeField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estadio', models.CharField(max_length=100)),
                ('respuestas', models.ManyToManyField(to='surveys.pregunta')),
            ],
        ),
    ]
