# Generated by Django 4.1.7 on 2023-03-12 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_estado_encuesta_activa_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=2000)),
                ('fecha_respuesta', models.DateTimeField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.user')),
            ],
        ),
    ]
