# Generated by Django 4.1.7 on 2023-03-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_pregunta_tipo_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha_expiracion',
        ),
    ]
