# Generated by Django 4.1.7 on 2023-03-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_pregunta_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Multiples', 'Multiples'), ('Unico', 'Unico'), ('Numero', 'Numero'), ('Email', 'Email')], max_length=100),
        ),
    ]
