# Generated by Django 4.1.7 on 2023-03-14 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_pregunta_activa_alter_pregunta_tipo_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasLimitadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_adicional_1', models.CharField(max_length=100)),
                ('campo_adicional_2', models.CharField(max_length=100)),
                ('campo_adicional_3', models.CharField(max_length=100)),
                ('campo_adicional_4', models.CharField(max_length=100)),
                ('campo_adicional_5', models.CharField(max_length=100)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta')),
            ],
        ),
    ]
