# Generated by Django 4.1.7 on 2023-03-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_preguntaslimitadas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreguntasLimitadas',
        ),
    ]
