# Generated by Django 4.1.7 on 2023-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_delete_preguntaslimitadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='estadio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
