# Generated by Django 4.1.7 on 2023-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_user_edad_alter_user_estadio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
