# Generated by Django 4.1.7 on 2023-03-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_alter_user_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='respuestas',
            new_name='respuesta',
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='surveys.user'),
        ),
    ]
